export enum Color {
    Color = 0,
    BlackAndWhite = 1,
    Colorized = 2
}

export enum Genre {
    Action = 0,
    Adventure = 1,
    Animation = 2,
    Biography = 3,
    Comedy = 4,
    Crime = 5,
    Documentary = 6,
    Drama = 7,
    Family = 8,
    Fantasy = 9,
    FilmNoir = 10,
    History = 12,
    Horror = 13,
    Music = 14,
    Musical = 15,
    Mystery = 16,
    Romance = 19,
    SciFi = 20,
    Sport = 21,
    Thriller = 23,
    War = 24,
    Western = 25,

    _GameShow = 11,
    _News = 17,
    _RealityTv = 18,
    _TalkShow = 22
}

export enum Group {
    _Top100 = 0,
    _Top250 = 1,
    _Top1000 = 2,
    _NowPlaying = 3,
    OscarWinner = 4,
    OscarNominee = 5,
    EmmyWinner = 8,
    EmmyNominee = 9,
    GoldenGlobeWinner = 10,
    GoldenGlobeNominee = 11,
    BestPictureWinner = 6,
    BestPictureNominee = 12,
    BestDirectorWinner = 7,
    BestDirectorNominee = 13
}

export enum SortType {
    PopularityDesc = 0,
    PopularityAsc = 1,
    UserRatingDesc = 3,
    UserRatingAsc = 2,
    NumVotesDesc = 5,
    NumVotesAsc = 4,
    ReleaseDateDesc = 7,
    ReleaseDateAsc = 6,
    BoxOfficeDesc = 8,
    BoxOfficeAsc = 9
}

export enum TitleType {
    Feature = 0,
    TvSeries = 2,
    MiniSeries = 5,
    Documentary = 6,
    Short = 8,
    Game = 7,

    //Video = 9,
    //TvShort = 10,
    //TvMovie = 1,
    //TvEpisode = 3,
    //TvSpecial = 4,
}

export enum Language {
    English,
    Turkish,
    Arabic,
    Bulgarian,
    Chinese,
    Croatian,
    Dutch,
    Finnish,
    French,
    German,
    Greek,
    Hebrew,
    Hindi,
    Hungarian,
    Icelandic,
    Italian,
    Japanese,
    Korean,
    Norwegian,
    Persian,
    Polish,
    Portuguese,
    Punjabi,
    Romanian,
    Russian,
    Spanish,
    Swedish,
    Ukrainian,
}

export enum Country {
    UnitedStates,
    Turkey,
    Argentina,
    Australia,
    Austria,
    Azerbaijan,
    Belgium,
    Brazil,
    Bulgaria,
    Canada,
    China,
    Colombia,
    CostaRica,
    Croatia,
    Cyprus,
    CzechRepublic,
    Denmark,
    Egypt,
    Estonia,
    Finland,
    France,
    Germany,
    Greece,
    HongKong,
    Hungary,
    Iceland,
    India,
    Iran,
    Ireland,
    Italy,
    Japan,
    Malaysia,
    Mexico,
    Netherlands,
    NewZealand,
    Norway,
    Pakistan,
    Poland,
    Portugal,
    Romania,
    Russia,
    Serbia,
    Singapore,
    Slovakia,
    Slovenia,
    SouthAfrica,
    SouthKorea,
    Spain,
    Sweden,
    Switzerland,
    Thailand,
    Ukraine,
    UnitedKingdom
}

export enum Compnay {
    Netflix = 0,
    AmazonPrime = 1,
    CenturyFox = 2,
    Sony = 3,
    Dreamworks = 4,
    MGM = 5,
    Paramount = 6,
    Universal = 7,
    WaltDisney = 8,
    WarnerBros = 9
}
